# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linting:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install flake8
        if (Test-Path requirements.txt) {pip install -r requirements.txt}
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install pytest pytest-cov PyInstaller wheel
        if (Test-Path requirements.txt) {pip install -r requirements.txt}
    - name: Install simonsays
      run: |
        pip install ./pynput_local
        pip install .
    - name: Test with pytest
      run: |
        python run_tests.py
    - name: Test build executable with pyinstaller
      run: |
        python tools/create_exe.py

  linux-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install pytest pytest-cov PyInstaller wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest-xvfb
    - name: Install simonsays
      run: |
        pip install ./pynput_local
        pip install .
    - name: Test with pytest
      run: |
        python run_tests.py
    - name: Test build executable with pyinstaller
      run: |
        python tools/create_exe.py
